Registrable app bool
licenseware/licenseware-sdk-v2 pull request #266
Opened 2022-09-23 13:08 UTC by ClimenteA

2022-09-23 15:52 UTC, adrian-mih approved these changes

2022-09-26 06:57 UTC, meysam81 requested changes

2022-09-26 06:57 UTC, meysam81 commented on licenseware/app_builder/app_activation_route.py
> +            if not appvars["registrable"]:
This is a violation of DRY. The same logic happening 4 times; please put them in one place to make it easy to change if ever wanted.

2022-09-26 07:00 UTC, ClimenteA commented on licenseware/app_builder/app_activation_route.py
> +            if not appvars["registrable"]:
Those are different endpoint called on different events.

2022-10-06 09:57 UTC, closed without merging