Update kafka package
licenseware/licenseware-sdk-v2 pull request #279
Opened 2022-10-04 13:15 UTC by ClimenteA

2022-10-04 15:15 UTC, meysam81 requested changes

2022-10-04 15:15 UTC, meysam81 commented on Dockerfile
> +RUN echo ready!
Do not remove the blank line at the end, please. git works best with lines.

2022-10-04 15:15 UTC, meysam81 commented on licenseware/config/config.py
> +        env_file = ".env"
This line is better removed. In the production application, we don't provide anything from the `.env` file instead everything is passed to the app from environmental variables. The `pydantic==VERSION` should be in `requirements.txt` and `pydantic[dotenv]` in the extras. Check out the current `setup.py` to get a feeling of what I'm trying to say.

2022-10-05 05:25 UTC, ClimenteA commented
@meysam81 I added the requested changes

2022-11-02 14:07 UTC, closed without merging